name: Deploy to Vercel
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # <-- এখানে v3 থেকে v4 করা হয়েছে
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build Web
        run: flutter build web --release
        
      - name: Copy vercel.json to build/web
        run: cp vercel.json build/web/
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25  # <-- এখানে v20 থেকে v25 করা হয়েছে
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./build/web
          vercel-args: '--prod'